### ISSUE TITLE
internal server error wehn dropping into the end portal

### ISSUE THREAD

**Issue by ZEROX7** [MinecraftschurliMods/Ars-Magica-Legacy#247]
hey there so after i killed the ender dragon and wished to go back i ran into a issue XD
it seems wehn you dont start ers magicka before killing the dragon you cant use the portal somethign about couldnt found mana level of entitiy

**Comment by ZEROX7** [comment]
Z3R0X1 joined the game
[20:28:59] [Server thread/INFO]: Sent config to 'Z3R0X1'.
[20:28:59] [Server thread/INFO]: Sending data to client: Z3R0X1
[20:28:59] [Server thread/INFO]: Not storing return portal because it's from ResourceKey[minecraft:dimension / minecraft:the_end] to ResourceKey[minecraft:dimension / minecraft:overworld]
[20:28:59] [Server thread/INFO]: Not storing return portal because it's from ResourceKey[minecraft:dimension / minecraft:the_end] to ResourceKey[minecraft:dimension / minecraft:overworld]
[20:28:59] [Server thread/INFO]: Not storing return portal because it's from ResourceKey[minecraft:dimension / minecraft:the_end] to ResourceKey[minecraft:dimension / minecraft:overworld]
[20:28:59] [Server thread/INFO]: Not storing return portal because it's from ResourceKey[minecraft:dimension / minecraft:the_end] to ResourceKey[minecraft:dimension / minecraft:overworld]
[20:28:59] [Server thread/ERROR]: Exception caught during firing event: Could not retrieve mana capability for LivingEntity Z3R0X1{4e669114-f7b0-4ff3-a844-4c0a340ad84f}
        Index: 6
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: NORMAL
                3: ASM: class dev.ftb.mods.ftbessentials.FTBEEventHandler playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: ASM: class com.endertech.minecraft.forge.world.GameWorld$WorldData onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: ASM: class net.mehvahdjukaar.supplementaries.common.events.ServerEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: net.minecraftforge.eventbus.EventBus$$Lambda$3955/0x00000008016c60f8@50b13b3b
                7: ASM: class com.endertech.minecraft.mods.adchimneys.world.Events onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 PufferFishAntiPoison(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: net.minecraftforge.eventbus.EventBus$$Lambda$3955/0x00000008016c60f8@694a8244
                10: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 CreeperSenseTimePause(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                11: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 SigilOfBaphometTime(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                12: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 Tick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                13: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 ExperienceBattery(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                14: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 SpeedForce(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                15: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 WoodenStickCD(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                16: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 IceCubeGround(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                17: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 VampireWeak(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                18: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 Blindfold(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                19: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 RageForce(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                20: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 CreeperSenseTime(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                21: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 Fertilizer(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                22: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 NelumboWalk(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                23: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 CreeperSense(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                24: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 SleepingPills(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                25: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 DarkNelumboWalk(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                26: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 EtherealWings(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                27: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 SpiderLegs(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                28: ASM: com.cozary.nameless_trinkets.event.EventHandler@1accda51 Reforger(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                29: ASM: class com.mrcrayfish.guns.common.ReloadTracker onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                30: ASM: se.mickelus.tetra.effect.ItemEffectHandler@66cfc8b5 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                31: ASM: class de.canitzp.solarhelmet.SolarHelmet$ForgeEvents updatePlayer(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                32: ASM: class com.maciej916.indreb.common.subscribers.events.PlayerTickEvent event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                33: ASM: class com.black_dog20.bml.internal.event.PlayerEventHandler onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                34: ASM: class com.black_dog20.bml.internal.event.ArmorEventHandler onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                35: ASM: class com.hollingsworth.arsnouveau.common.potions.GravityEffect entityTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                36: ASM: class com.hollingsworth.arsnouveau.common.items.curios.CuriosEventHandler playerOnTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                37: ASM: class com.hollingsworth.arsnouveau.common.event.ManaCapEvents onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                38: ASM: class com.hollingsworth.arsnouveau.common.event.ManaCapEvents playerOnTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                39: ASM: class com.endertech.minecraft.mods.adpother.events.PlayerEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                40: ASM: yaboichips.charms.util.events.CharmProperties@772335bf doCharms(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                41: ASM: net.jaspr.fasterladderclimbing.FasterLadderClimbing@3e136907 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                42: ASM: toughasnails.thirst.ThirstHandler@719ad779 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                43: ASM: toughasnails.temperature.TemperatureHandler@28893dee onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                44: ASM: class com.minecolonies.coremod.event.EventHandler onEnteringChunk(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                45: ASM: class com.simibubi.create.content.curiosities.bell.HauntedBellPulser hauntedBellCreatesPulse(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                46: ASM: snownee.everpotion.CoreModule@5b1f3ba3 tickPlayer(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                47: net.minecraftforge.eventbus.EventBus$$Lambda$3955/0x00000008016c60f8@574cfa12
                48: ASM: mcjty.lib.setup.ModSetup$EventHandler@5c8dcbba onPlayerTickEvent(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                49: ASM: mcjty.rftoolsutility.setup.ForgeEventHandlers@7739c0c9 onPlayerTickEvent(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                50: ASM: class paulojjj.solarenergy.TickHandler serverTick(Lnet/minecraftforge/event/TickEvent;)V
                51: LOW
                52: ASM: se.mickelus.tetra.items.forged.VibrationDebuffer@1837b19b onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                53: ASM: se.mickelus.tetra.advancements.BlockLookTrigger@270d7eb3 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                54: ASM: se.mickelus.tetra.items.modular.impl.toolbelt.booster.TickHandlerBooster@3b805d1e onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                55: LOWEST
                56: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler onGlideTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.RuntimeException: Could not retrieve mana capability for LivingEntity Z3R0X1{4e669114-f7b0-4ff3-a844-4c0a340ad84f}
        at TRANSFORMER/arsmagicalegacy@1.18.1-0.0.5/com.github.minecraftschurlimods.arsmagicalegacy.common.magic.ManaHelper.lambda$getManaHolder$2(ManaHelper.java:121)
        at TRANSFORMER/forge@39.0.20/net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:295)
        at TRANSFORMER/arsmagicalegacy@1.18.1-0.0.5/com.github.minecraftschurlimods.arsmagicalegacy.common.magic.ManaHelper.getManaHolder(ManaHelper.java:121)
        at TRANSFORMER/arsmagicalegacy@1.18.1-0.0.5/com.github.minecraftschurlimods.arsmagicalegacy.common.magic.ManaHelper.increaseMana(ManaHelper.java:69)
        at TRANSFORMER/arsmagicalegacy@1.18.1-0.0.5/com.github.minecraftschurlimods.arsmagicalegacy.common.EventHandler.playerTick(EventHandler.java:264)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@39.0.20/net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:851)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:207)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.Connection.m_129483_(Connection.java:233)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668)
        at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
        at java.base/java.lang.Thread.run(Thread.java:833)

[20:29:00] [Server thread/WARN]: Failed to handle packet for /195.202.216.8:60705
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Could not retrieve mana capability for LivingEntity Z3R0X1{4e669114-f7b0-4ff3-a844-4c0a340ad84f}
        at com.github.minecraftschurlimods.arsmagicalegacy.common.magic.ManaHelper.lambda$getManaHolder$2(ManaHelper.java:121) ~[arsmagicalegacy-1.18.1-0.0.5.jar%2352!:0.0.5]
        at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:295) ~[forge-1.18.1-39.0.20-universal.jar%23266!:?]
        at com.github.minecraftschurlimods.arsmagicalegacy.common.magic.ManaHelper.getManaHolder(ManaHelper.java:121) ~[arsmagicalegacy-1.18.1-0.0.5.jar%2352!:0.0.5]
        at com.github.minecraftschurlimods.arsmagicalegacy.common.magic.ManaHelper.increaseMana(ManaHelper.java:69) ~[arsmagicalegacy-1.18.1-0.0.5.jar%2352!:0.0.5]
        at com.github.minecraftschurlimods.arsmagicalegacy.common.EventHandler.playerTick(EventHandler.java:264) ~[arsmagicalegacy-1.18.1-0.0.5.jar%2352!:0.0.5]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPreTick(ForgeEventFactory.java:851) ~[forge-1.18.1-39.0.20-universal.jar%23266!:?]
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:207) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.1-20211210.034407-srg.jar%23262!:?]
        ... 9 more
[20:29:00] [Server thread/INFO]: Z3R0X1 lost connection: Internal server error
[20:29:00] [Server thread/INFO]: Z3R0X1 left the game

**Comment by IchHabeHunger54** [comment]
This is an issue we encountered in development as well, it has already been fixed in dev and will be published with the next update.
