### ISSUE TITLE
[Bug]: Kick from the server due to the use of the altar

### ISSUE THREAD

**Issue by YukiroAkihiki** [MinecraftschurliMods/Ars-Magica-Legacy#333]
### Describe the bug

The bug is that there is a server kick due to incorrect packets received from arsmagicalegacy.

### Steps to Reproduce

1. Create Open Server Lan
2. Connect to Server
3. Use Altar put book into lectern
4. Bug

### Expected behavior

no kick from the server and not issue an error about incorrect packages related to the creation of magic

### Screenshots

![image](https://user-images.githubusercontent.com/115872325/195980574-e6f5e801-d144-4a7c-b6f2-b179d3be571c.png)
![image](https://user-images.githubusercontent.com/115872325/195980590-f9348f95-390b-4988-9d00-462882fff74e.png)
![image](https://user-images.githubusercontent.com/115872325/195980824-b3c762b7-5ce8-4f98-976f-d9fc11ef3d8a.png)

### Version

1.19.2-1.1.5

### Forge Version

43.1.25

### Other Mods

- arsmagicalegacy-1.19.2-1.1.7-all
- Patchouli-1.19.2-76

### Log

```shell
[13:08:04] [main/INFO]: ModLauncher running: args [--username, _TheDES_, --version, Forge 1.19.2, --gameDir, C:\Users\komra\AppData\Roaming\.minecraft, --assetsDir, C:\Users\komra\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, 8cb365d13b1d4e7fa289fe1bd2173191, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, modified, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 43.1.25, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[13:08:05] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[13:08:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/komra/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[13:08:34] [main/INFO]: Found mod file arsmagicalegacy-1.19.2-1.1.7-all.jar of type MOD with provider {mods folder locator at C:\Users\komra\AppData\Roaming\.minecraft\mods}
[13:08:34] [main/INFO]: Found mod file Patchouli-1.19.2-76.jar of type MOD with provider {mods folder locator at C:\Users\komra\AppData\Roaming\.minecraft\mods}
[13:08:49] [main/WARN]: Mod file C:\Users\komra\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19.2-43.1.25\fmlcore-1.19.2-43.1.25.jar is missing mods.toml file
[13:08:50] [main/WARN]: Mod file C:\Users\komra\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.1.25\javafmllanguage-1.19.2-43.1.25.jar is missing mods.toml file
[13:08:50] [main/WARN]: Mod file C:\Users\komra\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.1.25\lowcodelanguage-1.19.2-43.1.25.jar is missing mods.toml file
[13:08:51] [main/WARN]: Mod file C:\Users\komra\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19.2-43.1.25\mclanguage-1.19.2-43.1.25.jar is missing mods.toml file
[13:08:54] [main/INFO]: Found mod file fmlcore-1.19.2-43.1.25.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6e78fcf5
[13:08:54] [main/INFO]: Found mod file javafmllanguage-1.19.2-43.1.25.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6e78fcf5
[13:08:54] [main/INFO]: Found mod file lowcodelanguage-1.19.2-43.1.25.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6e78fcf5
[13:08:54] [main/INFO]: Found mod file mclanguage-1.19.2-43.1.25.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6e78fcf5
[13:08:54] [main/INFO]: Found mod file client-1.19.2-20220805.130853-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6e78fcf5
[13:08:54] [main/INFO]: Found mod file forge-1.19.2-43.1.25-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6e78fcf5
[13:08:66] [main/INFO]: Found 4 dependencies adding them to mods collection
[13:08:66] [main/INFO]: Found mod file codeclib-1.19-1.0-SNAPSHOT.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@15fa55a6
[13:08:66] [main/INFO]: Found mod file simplenetlib-1.19-1.0-SNAPSHOT.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@15fa55a6
[13:08:66] [main/INFO]: Found mod file betterhudlib-1.19-1.0-SNAPSHOT.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@15fa55a6
[13:08:66] [main/INFO]: Found mod file betterkeybindlib-1.19-1.1-SNAPSHOT.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@15fa55a6
[13:08:74] [main/INFO]: Compatibility level set to JAVA_17
[13:08:74] [main/INFO]: Launching target 'forgeclient' with arguments [--version, Forge 1.19.2, --gameDir, C:\Users\komra\AppData\Roaming\.minecraft, --assetsDir, C:\Users\komra\AppData\Roaming\.minecraft\assets, --uuid, 8cb365d13b1d4e7fa289fe1bd2173191, --username, _TheDES_, --assetIndex, 1.19, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, modified, --width, 925, --height, 530]
[13:08:61] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[13:08:40] [Render thread/WARN]: Assets URL 'union:/C:/Users/komra/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23147!/assets/.mcassetsroot' uses unexpected schema
[13:08:40] [Render thread/WARN]: Assets URL 'union:/C:/Users/komra/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23147!/data/.mcassetsroot' uses unexpected schema
[13:08:43] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:08:00] [Render thread/INFO]: Setting user: _TheDES_
[13:08:14] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[13:08:64] [modloading-worker-0/INFO]: Forge mod loading, version 43.1.25, for MC 1.19.2 with MCP 20220805.130853
[13:08:64] [modloading-worker-0/INFO]: MinecraftForge v43.1.25 Initialized
[13:08:08] [modloading-worker-0/ERROR]: Failed to load: com.github.minecraftschurlimods.arsmagicalegacy.compat.theoneprobe.TOPCompat
java.lang.NoClassDefFoundError: mcjty/theoneprobe/api/IProbeInfoProvider
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at TRANSFORMER/arsmagicalegacy@1.19.2-1.1.7/com.github.minecraftschurlimods.arsmagicalegacy.compat.CompatManager.lambda$getClasses$1(CompatManager.java:117)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at TRANSFORMER/arsmagicalegacy@1.19.2-1.1.7/com.github.minecraftschurlimods.arsmagicalegacy.compat.CompatManager.getClasses(CompatManager.java:122)
	at TRANSFORMER/arsmagicalegacy@1.19.2-1.1.7/com.github.minecraftschurlimods.arsmagicalegacy.compat.CompatManager.discoverModCompats(CompatManager.java:104)
	at TRANSFORMER/arsmagicalegacy@1.19.2-1.1.7/com.github.minecraftschurlimods.arsmagicalegacy.compat.CompatManager.preInit(CompatManager.java:68)
	at TRANSFORMER/arsmagicalegacy@1.19.2-1.1.7/com.github.minecraftschurlimods.arsmagicalegacy.ArsMagicaLegacy.<init>(ArsMagicaLegacy.java:67)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at LAYER PLUGIN/javafmllanguage@1.19.2-43.1.25/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68)
	at LAYER PLUGIN/fmlcore@1.19.2-43.1.25/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: mcjty.theoneprobe.api.IProbeInfoProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 37 more

[13:08:38] [Render thread/INFO]: Narrator library for x64 successfully loaded
[13:08:41] [Render thread/INFO]: Reloading ResourceManager: Mod Resources, Default
[13:08:75] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[13:08:49] [Forge Version Check/INFO]: [forge] Found status: OUTDATED Current: 43.1.25 Target: 43.1.43
[13:08:68] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[13:08:68] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[13:08:72] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Динамики (2- Realtek(R) Audio)
[13:08:72] [Render thread/INFO]: Sound engine started
[13:08:93] [Render thread/INFO]: Created: 1024x1024x1 minecraft:textures/atlas/blocks.png-atlas
[13:08:94] [Render thread/INFO]: Created: 256x128x1 minecraft:textures/atlas/signs.png-atlas
[13:08:94] [Render thread/INFO]: Created: 512x512x1 minecraft:textures/atlas/banner_patterns.png-atlas
[13:08:94] [Render thread/INFO]: Created: 512x512x1 minecraft:textures/atlas/shield_patterns.png-atlas
[13:08:94] [Render thread/INFO]: Created: 256x256x1 minecraft:textures/atlas/chest.png-atlas
[13:08:94] [Render thread/INFO]: Created: 512x256x1 minecraft:textures/atlas/beds.png-atlas
[13:08:94] [Render thread/INFO]: Created: 512x256x1 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:08:75] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[13:08:09] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[13:08:09] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:08:09] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:08:10] [Render thread/INFO]: Created: 1024x512x0 arsmagicalegacy:textures/atlas/spell_icons.png-atlas
[13:08:10] [Render thread/INFO]: Created: 1024x512x0 arsmagicalegacy:textures/atlas/skill_icons.png-atlas
[13:08:10] [Render thread/INFO]: BookContentResourceListenerLoader preloaded 159 jsons
[13:08:10] [Render thread/INFO]: Not reloading resource pack-based books as client world is missing
[13:08:66] [Netty Client IO #2/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:68] [Netty Client IO #1/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:68] [Netty Client IO #0/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:68] [Netty Client IO #3/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:50] [Netty Client IO #4/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:99] [Netty Client IO #5/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:03] [Netty Client IO #10/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:06] [Netty Client IO #7/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:06] [Netty Client IO #8/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:07] [Netty Client IO #11/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:09] [Netty Client IO #12/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:10] [Netty Client IO #9/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:10] [Netty Client IO #14/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:11] [Netty Client IO #15/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:15] [Netty Client IO #16/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:18] [Netty Client IO #19/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:19] [Netty Client IO #20/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:25] [Netty Client IO #21/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:25] [Netty Client IO #6/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:29] [Server Pinger #0/ERROR]: Can't ping mc.dreamnw.ru: Unknown host
[13:08:33] [Netty Client IO #18/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:40] [Netty Client IO #23/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:44] [Netty Client IO #2/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:46] [Netty Client IO #22/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:55] [Netty Client IO #3/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:00] [Netty Client IO #0/ERROR]: Channels [patchouli:main,arsmagicalegacy:main] rejected vanilla connections
[13:08:14] [Render thread/INFO]: Connecting to 26.85.195.208, 62124
[13:09:71] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[13:09:36] [Netty Client IO #5/INFO]: Connected to a modded server.
[13:09:60] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:60] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:60] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:61] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:61] [Render thread/INFO]: Loaded 31 advancements
[13:09:61] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:61] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:61] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:61] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:61] [Render thread/INFO]: BookContentResourceListenerLoader: Files found in 1.052 ms
[13:09:62] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:62] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:62] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:62] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:62] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:63] [Render thread/INFO]: BookContentResourceListenerLoader: Files found in 613.1 ?s
[13:09:63] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:64] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:64] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:65] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:68] [Render thread/INFO]: BookContentResourceListenerLoader: Files found in 507.6 ?s
[13:09:69] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:72] [Netty Client IO #5/ERROR]: Received invalid discriminator byte 255 on channel arsmagicalegacy:main
[13:09:72] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:74] [Render thread/WARN]: Unknown custom packet identifier: arsmagicalegacy:main
[13:09:11] [Netty Client IO #5/ERROR]: Received empty payload on channel arsmagicalegacy:main
[13:09:11] [Netty Client IO #5/ERROR]: Received invalid discriminator byte 3 on channel arsmagicalegacy:main
[13:09:13] [Render thread/WARN]: Unknown custom packet identifier: arsmagicalegacy:main
[13:09:02] [Sound engine/ERROR]: Stop: Invalid name parameter.
```

**Comment by IchHabeHunger54** [comment]
Please define "use altar" more exactly. Are you placing the altar core? Are you putting a book into the lectern? Are you throwing an item in?

That being said, this looks to me like a mismatch of modded/vanilla servers (or of different modpacks). Does the server have the same AM:L version?

**Comment by YukiroAkihiki** [comment]
throwing item or put book into lectern and also when the book is on lectern
the version is the same
crashes only when several players are standing at the altar and book is on lectern

**Comment by Minecraftschurli** [comment]
Does this still occur on the latest version?

**Comment by IchHabeHunger54** [comment]
Closed due to inactivity.
