### ISSUE TITLE
[Bug]: Inscription Table crash

### ISSUE THREAD

**Issue by BSCoding0** [MinecraftschurliMods/Ars-Magica-Legacy#372]
### Describe the bug

There is a crash if you put to many modifiers (the one I put in was "range") into the bottom slot of the Inscription Table.

### Steps to Reproduce

Put in a "Projectile" Modifier into one of the top parts and a "Explosion" Spell into the bottom one.
After that add as many "Range" Modifiers as possible into the bottom slots.
-> crash

### Version

1.19.2-1.2.4

### Forge Version

1.19.2

### Other Mods

Patchouli-1.19.2-77.jar

jei-1.19.2-forge-11.5.2.1007.jar

geckolib-forge-1.19-3.1.39.jar

Controlling-forge-1.19.2-10.0+7.jar

arsmagicalegacy-1.19.2-1.2.4.jar

appleskin-forge-mc1.19-2.4.2.jar

### Log

```shell
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-01-30 20:29:15
Description: mouseReleased event handler

java.lang.RuntimeException: Encountered an issue with drag & drop!
	at com.github.minecraftschurlimods.arsmagicalegacy.client.gui.dropdis.BasicDropZone.setPositionAndSize(BasicDropZone.java:116) ~[arsmagicalegacy-1.19.2-1.2.4.jar%23152!/:1.2.4] {re:classloading}
	at com.github.minecraftschurlimods.arsmagicalegacy.client.gui.dropdis.BasicDropZone.add(BasicDropZone.java:56) ~[arsmagicalegacy-1.19.2-1.2.4.jar%23152!/:1.2.4] {re:classloading}
	at com.github.minecraftschurlimods.arsmagicalegacy.client.gui.dropdis.DropArea.m_6348_(DropArea.java:57) ~[arsmagicalegacy-1.19.2-1.2.4.jar%23152!/:1.2.4] {re:classloading}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_94704_(ContainerEventHandler.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,re:mixin}
	at java.util.Optional.filter(Optional.java:218) ~[?:?] {}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6348_(ContainerEventHandler.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,re:mixin}
	at com.github.minecraftschurlimods.arsmagicalegacy.client.gui.dropdis.DragPane.m_6348_(DragPane.java:47) ~[arsmagicalegacy-1.19.2-1.2.4.jar%23152!/:1.2.4] {re:classloading}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_94704_(ContainerEventHandler.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,re:mixin}
	at java.util.Optional.filter(Optional.java:218) ~[?:?] {}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6348_(ContainerEventHandler.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6348_(AbstractContainerScreen.java:428) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at com.github.minecraftschurlimods.arsmagicalegacy.client.gui.InscriptionTableScreen.m_6348_(InscriptionTableScreen.java:277) ~[arsmagicalegacy-1.19.2-1.2.4.jar%23152!/:1.2.4] {re:classloading}
	at net.minecraft.client.MouseHandler.m_168078_(MouseHandler.java:96) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.minecraftschurlimods.arsmagicalegacy.client.gui.dropdis.BasicDropZone.setPositionAndSize(BasicDropZone.java:116) ~[arsmagicalegacy-1.19.2-1.2.4.jar%23152!/:1.2.4] {re:classloading}
	at com.github.minecraftschurlimods.arsmagicalegacy.client.gui.dropdis.BasicDropZone.add(BasicDropZone.java:56) ~[arsmagicalegacy-1.19.2-1.2.4.jar%23152!/:1.2.4] {re:classloading}
	at com.github.minecraftschurlimods.arsmagicalegacy.client.gui.dropdis.DropArea.m_6348_(DropArea.java:57) ~[arsmagicalegacy-1.19.2-1.2.4.jar%23152!/:1.2.4] {re:classloading}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_94704_(ContainerEventHandler.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,re:mixin}
	at java.util.Optional.filter(Optional.java:218) ~[?:?] {}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6348_(ContainerEventHandler.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,re:mixin}
	at com.github.minecraftschurlimods.arsmagicalegacy.client.gui.dropdis.DragPane.m_6348_(DragPane.java:47) ~[arsmagicalegacy-1.19.2-1.2.4.jar%23152!/:1.2.4] {re:classloading}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_94704_(ContainerEventHandler.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,re:mixin}
	at java.util.Optional.filter(Optional.java:218) ~[?:?] {}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6348_(ContainerEventHandler.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6348_(AbstractContainerScreen.java:428) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at com.github.minecraftschurlimods.arsmagicalegacy.client.gui.InscriptionTableScreen.m_6348_(InscriptionTableScreen.java:277) ~[arsmagicalegacy-1.19.2-1.2.4.jar%23152!/:1.2.4] {re:classloading}
	at net.minecraft.client.MouseHandler.m_168078_(MouseHandler.java:96) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
-- Affected screen --
Details:
	Screen name: com.github.minecraftschurlimods.arsmagicalegacy.client.gui.InscriptionTableScreen
Stacktrace:
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['BS_Animation'/282, l='ClientLevel', x=-281.07, y=111.00, z=92.20]]
	Chunk stats: 961, 616
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,86,32), Section: (at 0,6,0 in 0,5,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 10664 game time, 10664 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:450) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2278) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:717) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1566693800 bytes (1494 MiB) / 3489660928 bytes (3328 MiB) up to 6576668672 bytes (6272 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2080 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e81
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2824
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28672.06
	Virtual memory used (MB): 25514.34
	Swap memory total (MB): 12350.58
	Swap memory used (MB): 1136.92
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6272m -Xms256m
	Launched Version: forge-43.2.0
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.24, NVIDIA Corporation
	Window size: 3440x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['BS_Animation'/282, l='ServerLevel[New World]', x=-281.07, y=111.00, z=92.20]]
	Data Packs: vanilla, mod:forge, mod:arsmagicalegacy (incompatible), mod:patchouli (incompatible), mod:geckolib3 (incompatible), mod:appleskin, mod:controlling (incompatible), mod:jei (incompatible)
	World Generation: Experimental
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		arsmagicalegacy-1.19.2-1.2.4.jar                  |Ars Magica: Legacy            |arsmagicalegacy               |1.19.2-1.2.4        |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.39.jar                    |GeckoLib                      |geckolib3                     |3.1.39              |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.19.2-10.0+7.jar               |Controlling                   |controlling                   |10.0+7              |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.5.2.1007.jar                  |Just Enough Items             |jei                           |11.5.2.1007         |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 549a5c07-d7e8-43c6-9a0a-ff03ab5d6355
	FML: 43.2
	Forge: net.minecraftforge:43.2.0
```

**Comment by IchHabeHunger54** [comment]
Similar issue as with #371: the inscription table is an internal mess and in need of a rework. Will be fixed, but with no guarantees as to when. For now, I'm afraid I can't do anything other than advising you to avoid this particular cause for a crash.
