### ISSUE TITLE
[Bug]: Crash on startup

### ISSUE THREAD

**Issue by Michaela-Blum** [MinecraftschurliMods/Ars-Magica-Legacy#406]
### Describe the bug

Crash on startup

### Steps to Reproduce

Try to start version 1.3

### Expected behavior

No crash

### Version

1.19.2-1.3.0

### Forge Version

43.2.0

### Other Mods

patchouli 1.19.2-77
geckolib-forge-1.19-3.1.40.jar

### Log

```shell
[11:43:02] [main/INFO]: ModLauncher running: args [--username, Michaela_Blum, --version, forge-43.2.0, --gameDir, C:\Users\Nina\curseforge\minecraft\Instances\Ars Magica, --assetsDir, C:\Users\Nina\curseforge\minecraft\Install\assets, --assetIndex, 1.19, --uuid, 1672d49a4fd942b8b9391b9d32faf322, --accessToken, ????????, --clientId, NDNmM2EwNmUtZWRiNi00OWRhLWI5ZmUtZGQ0MWE3ZDg1MTk2, --xuid, 2535428089507919, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.0, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[11:43:02] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[11:43:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Nina/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2397!/ Service=ModLauncher Env=CLIENT
[11:43:02] [main/INFO]: Found mod file arsmagicalegacy-1.19.2-1.3.0-SNAPSHOT.jar of type MOD with provider {mods folder locator at C:\Users\Nina\curseforge\minecraft\Instances\Ars Magica\mods}
[11:43:02] [main/INFO]: Found mod file geckolib-forge-1.19-3.1.40.jar of type MOD with provider {mods folder locator at C:\Users\Nina\curseforge\minecraft\Instances\Ars Magica\mods}
[11:43:02] [main/INFO]: Found mod file Patchouli-1.19.2-77.jar of type MOD with provider {mods folder locator at C:\Users\Nina\curseforge\minecraft\Instances\Ars Magica\mods}
[11:43:02] [main/WARN]: Mod file C:\Users\Nina\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.0\fmlcore-1.19.2-43.2.0.jar is missing mods.toml file
[11:43:02] [main/WARN]: Mod file C:\Users\Nina\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.0\javafmllanguage-1.19.2-43.2.0.jar is missing mods.toml file
[11:43:02] [main/WARN]: Mod file C:\Users\Nina\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.0\lowcodelanguage-1.19.2-43.2.0.jar is missing mods.toml file
[11:43:02] [main/WARN]: Mod file C:\Users\Nina\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.0\mclanguage-1.19.2-43.2.0.jar is missing mods.toml file
[11:43:02] [main/INFO]: Found mod file fmlcore-1.19.2-43.2.0.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[11:43:02] [main/INFO]: Found mod file javafmllanguage-1.19.2-43.2.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[11:43:02] [main/INFO]: Found mod file lowcodelanguage-1.19.2-43.2.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[11:43:02] [main/INFO]: Found mod file mclanguage-1.19.2-43.2.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[11:43:02] [main/INFO]: Found mod file client-1.19.2-20220805.130853-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[11:43:02] [main/INFO]: Found mod file forge-1.19.2-43.2.0-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[11:43:02] [main/INFO]: Found 4 dependencies adding them to mods collection
[11:43:02] [main/INFO]: Found mod file codeclib-1.19-1.0-SNAPSHOT.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@30506c0d
[11:43:02] [main/INFO]: Found mod file simplenetlib-1.19-1.0-SNAPSHOT.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@30506c0d
[11:43:02] [main/INFO]: Found mod file betterhudlib-1.19-1.0-SNAPSHOT.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@30506c0d
[11:43:02] [main/INFO]: Found mod file betterkeybindlib-1.19-1.1-SNAPSHOT.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@30506c0d
[11:43:03] [main/INFO]: Compatibility level set to JAVA_17
[11:43:03] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-43.2.0, --gameDir, C:\Users\Nina\curseforge\minecraft\Instances\Ars Magica, --assetsDir, C:\Users\Nina\curseforge\minecraft\Install\assets, --uuid, 1672d49a4fd942b8b9391b9d32faf322, --username, Michaela_Blum, --assetIndex, 1.19, --accessToken, ????????, --clientId, NDNmM2EwNmUtZWRiNi00OWRhLWI5ZmUtZGQ0MWE3ZDg1MTk2, --xuid, 2535428089507919, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[11:43:05] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[11:43:06] [Render thread/WARN]: Assets URL 'union:/C:/Users/Nina/curseforge/minecraft/Install/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23157!/assets/.mcassetsroot' uses unexpected schema
[11:43:06] [Render thread/WARN]: Assets URL 'union:/C:/Users/Nina/curseforge/minecraft/Install/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23157!/data/.mcassetsroot' uses unexpected schema
[11:43:06] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:43:08] [Render thread/INFO]: Setting user: Michaela_Blum
[11:43:08] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[11:43:08] [modloading-worker-0/INFO]: Forge mod loading, version 43.2.0, for MC 1.19.2 with MCP 20220805.130853
[11:43:08] [modloading-worker-0/INFO]: MinecraftForge v43.2.0 Initialized
[11:43:08] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: arsmagicalegacy, class com.github.minecraftschurlimods.arsmagicalegacy.ArsMagicaLegacy
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23159!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23158!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoSuchFieldError: CUSTOM_STAT_REGISTRY
	at com.github.minecraftschurlimods.arsmagicalegacy.common.init.AMRegistries.<clinit>(AMRegistries.java:68) ~[arsmagicalegacy-1.19.2-1.3.0-SNAPSHOT.jar%23154!/:1.3.0]
	at com.github.minecraftschurlimods.arsmagicalegacy.ArsMagicaLegacy.<init>(ArsMagicaLegacy.java:62) ~[arsmagicalegacy-1.19.2-1.3.0-SNAPSHOT.jar%23154!/:1.3.0]
	... 14 more
[11:43:09] [Render thread/FATAL]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Block to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Item to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RenderLevelStageEvent$RegisterStageEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterParticleProvidersEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterTextureAtlasSpriteLoadersEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientTooltipComponentFactoriesEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterEntitySpectatorShadersEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterKeyMappingsEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterRecipeBookCategoriesEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterGuiOverlaysEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterDimensionSpecialEffectsEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterNamedRenderTypesEvent to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$ColorResolvers to a broken mod state
[11:43:09] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterItemDecorationsEvent to a broken mod state
[11:43:09] [Render thread/INFO]: Reloading ResourceManager: Default
[11:43:09] [Worker-Main-4/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:43:09] [Worker-Main-13/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:43:09] [Worker-Main-10/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:43:09] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterGeometryLoaders to a broken mod state
[11:43:13] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterAdditional to a broken mod state
[11:43:13] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:43:14] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:43:14] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:43:14] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:43:14] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:43:14] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:43:14] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[11:43:14] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[11:43:14] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[11:43:14] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Headphones (Realtek(R) Audio)
[11:43:14] [Render thread/INFO]: Sound engine started
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[11:43:14] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:43:14] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:43:14] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:43:14] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:43:14] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:43:14] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:43:14] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$BakingCompleted to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[11:43:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state
[11:43:15] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[11:43:15] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterShadersEvent to a broken mod state
[11:43:15] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[11:43:15] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:43:15] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[11:43:15] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:43:15] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[11:43:15] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[11:43:15] [Render thread/FATAL]: Preparing crash report with UUID bdeab3cb-6496-4ea4-8a49-27f6d99bbab8
[11:43:15] [Render thread/FATAL]: Crash report saved to C:\Users\Nina\curseforge\minecraft\Instances\Ars Magica\crash-reports\crash-2023-07-30_11.43.15-fml.txt
[11:43:15] [Render thread/FATAL]: Preparing crash report with UUID 8ceba448-a166-48f2-8e87-a0e57eeccd34
```

**Comment by Minecraftschurli** [comment]
@IchHabeHunger54 Seems like the mod jar used here is not obfuscated
@Michaela-Blum Can you give us the exact jar of AM:L you were using

**Comment by IchHabeHunger54** [comment]
@Minecraftschurli Full name is in the logs (`arsmagicalegacy-1.19.2-1.3.0-SNAPSHOT`)

**Comment by Michaela-Blum** [comment]
[arsmagica-upload.zip](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/files/12215999/arsmagica-upload.zip)
Here you go, I zipped it so github would accept it.

**Comment by Minecraftschurli** [comment]
Where did you download that from?

**Comment by Michaela-Blum** [comment]
From the curseforge launcher

**Comment by Minecraftschurli** [comment]
I have taken down the broken version and I'm uploading the correct one (hopefully). Should be available within the next 2 hours.
